feat(db): add Review model to db
platanus/the-store2 pull request #1
Opened 2022-12-26 16:08 UTC by vicentematus

### Contexto

El problema es el siguiente: se necesita crear un nuevo modelo Review, que relaciona un usuario con un producto. Con los siguientes atributos:
- user_id
- item_id
- body

[Ver enunciado](https://www.notion.so/platanus/Agregar-reviews-a-los-productos-e55e8851b1a342b7a1b65dbffd8b91fa)

### Qué se esta haciendo

Al inicio se corrieron las migraciones pendientes con `bin/rails db:schema:load`. Posteriormente para crear el modelo se uso el comando `bin/rails generate model Review users:references items:references body:string`. Se corrieron las migraciones con `db:migrate` y se checkearon si estaban todas bien con `db:migrate:status`.

#### En particular hay que revisar

Si la creacion del modelo fue correcta y con tiene los atributos necesarios.

2022-12-26 17:27 UTC, difernandez requested changes
Bacán usar el generador de modelos de rails, es bien útil 💯 dejé algunos detalles

2022-12-26 17:27 UTC, difernandez commented on app/models/review.rb
> +  belongs_to :items
- Debería ser en singular, `user` e `item`. El plural es cuando son varios, osea con los `has_many`. Esto debe ser a nivel de migración también
- Agregaría las otras partes de las relaciones, osea los `has_many` en users e items, para que sea explícito en ambos lados

2022-12-26 17:27 UTC, difernandez commented on spec/models/review_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
en los tests de modelos debería siempre al menos haber un test que prueba que la factory esté bien definida. Puedes ver un [ejemplo en el purchase](https://github.com/platanus/the-store2/blob/master/spec/models/purchase_spec.rb). De hecho, en este caso me tinca que tiraría error, ya que `user` y `item` están como `nil` en la factory, y por defecto el `belongs_to` los deja como requeridos

2022-12-26 20:39 UTC, monkeyci commented on app/models/item.rb
> +  has_many :reviews
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/HasManyOrHasOneDependent: Specify a :dependent option.

2022-12-26 20:39 UTC, monkeyci commented on app/models/user.rb
> +  has_many :reviews
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/HasManyOrHasOneDependent: Specify a :dependent option.

2022-12-26 20:39 UTC, monkeyci commented on spec/factories/reviews.rb
> +    user
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2022-12-26 21:17 UTC, rjherrera approved these changes

2022-12-27 13:49 UTC, difernandez approved these changes

2022-12-27 13:50 UTC, merged