Feat/review form
platanus/the-store2 pull request #5
Opened 2023-01-10 23:57 UTC by vicentematus

### Contexto

- Se debe agregar un formulario para los reviews
- Si el usuario agrego un review, entonces no debería mostrar el formulario del item.
- Cuando el usuario agregue un review, no debería actualizar la página y solamente debería actualizar el listado.
- Se debe crear un endpoint para el modelo de Reviews para así permitir la creación de estas.

[Ver enunciado](https://www.notion.so/platanus/Agregar-reviews-a-los-productos-e55e8851b1a342b7a1b65dbffd8b91fa)
[Ver Figma](https://www.figma.com/file/TUBICpcfyhq9ZkNRXTwJhx/Proyecto-Trainees---Tienda-de-muebles?node-id=306%3A2459&t=mvhPrX0rzZmWiRzG-1)

### Qué se esta haciendo

- Se creo un controlador de Reviews con el generador de Power API
- Se agrega el type de User para poder mostrar el email (todavía no esta el nice-to-have del name)
- Se agrega el metodo create para la api de Reviews y el type de este también.
- Se modifica el controlador de items para poder incluir el usuario en los reviews. Por esa razón se entrega en una variable aparte.
- Se modifica el controlador de items para agregar el current_user así podemos saber si el usuario ya ingresó un review o no.
- Se agrega un formulario `item-view-review-form`el cual permite al usuario ingresar un review al producto. Temporalmente en rating devuelve un valor 4 (el select de estrella esta en desarrollo)
- Se modifica el item-view para que el listado de reviews sea un ref, así se pueda ir actualizando dinamicamente.
- Se agrega un computed property que permite verificar si del listado de reviews existentes, el usuario ya agregó una review. En el caso de que lo haya hecho, no mostrará el formulario y dirá un mensaje de que ya agregó reviews.
- En el formulario si el usuario agrega un review, se hará un emit de un evento al componente de item-view, el cual actualizará la lista sin la necesidad de darle refresh a la página.  Se agrega como unshift para que así sea el primero en la lista al momento de agregarlo.
- Se agrega un toggle el cual nos permitirá mostrar o esconder el formulario al momento de hacer click.

#### En particular hay que revisar

- Si la creación del controlador esta correcta.
- Si el uso de eventos en el formulario está correcto. Es decir los emits al componente item-view y así.
- Si la encapsulación del item-view-review-form está correcta. Es decir el uso de apis, y el dispatch de eventos.
- Si el uso de las computes properties y el uso de ref en la lista está bien implementado.
- Que los test funcionen correctamente (work in progress)
- Si la encapsulación de los componentes está correcta

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

https://user-images.githubusercontent.com/38754555/211686542-78e8ccde-f074-4cec-b031-e7e8667a6ad7.mp4

2023-01-11 18:21 UTC, monkeyci commented on app/controllers/api/internal/reviews_controller.rb
> +    respond_with Review.all
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 5

2023-01-11 18:21 UTC, monkeyci commented on app/controllers/api/internal/reviews_controller.rb
> +    respond_with review
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 9

2023-01-11 18:21 UTC, monkeyci commented on app/controllers/api/internal/reviews_controller.rb
> +    @review ||= Review.find_by!(id: params[:id])
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 19

2023-01-11 18:57 UTC, ttapia requested changes
Dejé varios comentarios! Cualquier cosa me cuentas!

2023-01-11 18:57 UTC, ttapia commented on app/serializers/review_serializer.rb
> +  belongs_to :item
aquí un detallin nomás, no es necesario mantener dos serializers iguales, uno en `app/serializers` y otro en `app/serializers/api/internal` si es que estay usando el método `serialize_resource` para pasarle el recurso a la componente de vue. Ese método es un helper de power_api y por detrás lo que hace por defecto es buscar el serializer que está en la carpeta `app/serializers/api/internal`. Podi ver la implementación [acá](https://github.com/platanus/power_api/blob/master/app/helpers/power_api/application_helper.rb)

2023-01-11 18:57 UTC, ttapia commented on config/routes.rb
> +      resources :reviews
Cuando teni un `resources` suelto, te genera todas las acciones default (new, create, edit, update, delete, index y show). Es mejor explicitarlo cuando no teni todas las acciones, podrías dejarlo usando solo lo relevante como `only: :create`

2023-01-11 18:57 UTC, ttapia commented on app/javascript/api/reviews.ts
> +}
Podrías ahorrarte este tipo `ReviewForm` si usas un [`Partial`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype). Un `Partial` es algo que te permite indicar que un objeto va a tener un subconjunto de las propiedades de un tipo. Entonces por ejemplo podrías tener algo así

```ts
export default {
  create(review: Partial<Review>) {
    const path = '/api/internal/reviews';

...
```

Pero igual pensandolo bien como le pusiste un posible null al body, esa diferencia quizás vale la pena tener la diferencia de tipos. Igual creo que si puede ser null en el form, también debería poder ser null en el tipo que se muestra, aunque quizás me falta contexto.

2023-01-11 18:57 UTC, ttapia commented on app/controllers/app/items_controller.rb
> +    @item ||= Item.includes(:reviews).find(params[:id])
Este cambio no está haciendo nada realmente, porque igual el @item solo se define acá y usarlo abajo no hará que se llame de nuevo al `find`.

Cuando esto sirve es cuando tienes definido un método como 

```ruby
def item
  @item ||= Item.includes(:reviews).find(params[:id])
end
```
y luego llamas a item mas de una vez en el código. Eso haría que la primera vez que se llama se setea la variable `@item` y luego las siguientes veces se usa el resultado cacheado.

2023-01-11 18:57 UTC, ttapia commented on app/controllers/app/items_controller.rb
> +    current_user
Este `current_user` _creo_ que no hace nada, tengo entendido que el método helper `current_user` debería estar disponible en la vista de rails y llamarlo acá no hace ninguna diferencia

2023-01-11 18:57 UTC, ttapia commented on app/controllers/app/items_controller.rb
> +    @reviews = @item.reviews.order(created_at: :desc).includes([:user])
cuando el includes tiene una sola cosa se puede llamar sin el `[]`, como así `includes(:user)`

2023-01-11 18:57 UTC, ttapia commented on app/javascript/components/item-view-review-comment.vue
> +  user: string,
está medio raro que la prop se llame `user` pero sea un string. Vi que le estay pasando el mail asi que sería mejor que el nombre de la prop sea más explícito, como `userEmail: string` (y ahí si hace sentido que sea un string)

2023-01-11 18:57 UTC, ttapia commented on app/javascript/components/item-view-review-form.vue
> +    // window.location.href = `/items/${form.itemId}`;
aca se te paso un comentario creo (?)

2023-01-11 18:57 UTC, ttapia commented on app/javascript/components/item-view-review-form.vue
> +      class="rounded-lg  border border-zinc-300 px-4 py-3 shadow-sm  focus:outline-none"
aca creo que hay varios espacios de más entre algunas clases

2023-01-11 18:57 UTC, ttapia commented on app/javascript/components/item-view-review-form.vue
> +      Ha ocurrido un error, porfavor intente nuevamente.
creo que debería ser `por favor`

2023-01-11 18:57 UTC, ttapia commented on app/views/app/items/show.html.erb
> +<item-view :item="<%= serialize_resource(@item) %>"
creo que se ve más ordenado dejando cada prop en una nueva linea, y en la primera solo el nombre de la componente, algo como:

```
<item-view
  :item=...
  :user=...
```

2023-01-11 18:57 UTC, ttapia commented on app/javascript/components/item-view.vue
> +const existReviewUser = computed(() => listReviews.value.some(review => review.userId === props.user.id));
creo que la variable podría tener un mejor nombre, algo como `userReviewExists` o `alreadyReviewed` o nose jaja, como que gramaticalmente `existReviewUser` no me hace mucho sentido, quizás podria ser algo como `existUserReview`, qué opinas?

2023-01-11 18:57 UTC, ttapia commented on spec/requests/api/internal/reviews_spec.rb
> -  describe 'GET /index' do
Quizás seria bueno meter estos cambios en el primer commit, en general meter cambios que se agregan y se quitan en el mismo PR es medio malo, porque podría haberte comentado que estos tests no servían en el primer commit porque no tenías un método de index. En general esa consistencia dentro de un commit/PR es para hacerle la vida más facil al revisor igual

2023-01-11 19:13 UTC, ldlsegovia reviewed
Un par de cosas nada más. El joven @ttapia fue bien exhaustivo  👏🏻

2023-01-11 19:13 UTC, ldlsegovia commented on app/controllers/api/internal/reviews_controller.rb
> +    respond_with Review.create!(review_params.merge(user: current_user))
Acá podés crear a través de las relaciones `current_user.reviews.create!(review_params)` 

https://github.com/platanus/the-store2/blob/master/app/models/user.rb#L8

2023-01-11 19:13 UTC, ldlsegovia commented on app/serializers/api/internal/review_serializer.rb
> +  belongs_to :item
Cuestión de gustos nada más pero pondría las relaciones después de type. Como para dejarlo parecido a los modelos

2023-01-11 20:18 UTC, vicentematus commented on app/javascript/components/item-view.vue
> +const existReviewUser = computed(() => listReviews.value.some(review => review.userId === props.user.id));
existUserReview tiene más sentido! todaLaRazon 😉

2023-01-11 20:23 UTC, vicentematus commented on app/controllers/api/internal/reviews_controller.rb
> +    respond_with Review.create!(review_params.merge(user: current_user))
está bueno esto 😮

2023-01-11 20:51 UTC, vicentematus commented on spec/requests/api/internal/reviews_spec.rb
> -  describe 'GET /index' do
Toda la razón, este cambio tenia que haber estado con la generación de PowerAPI para que no perdiera el contexto 😸 !

2023-01-11 20:56 UTC, vicentematus commented on app/controllers/app/items_controller.rb
> +    @item ||= Item.includes(:reviews).find(params[:id])
En este caso cómo lo podría hacer para volver atrás? Tendría que hacer un git reset head y reestructurar los commits? o no sería necesario 🤔

2023-01-11 20:57 UTC, vicentematus commented on app/javascript/api/reviews.ts
> +}
Lo agregué de todas maneras. No conocia la propiedad Partial de typescript 😮 , está bueno en el caso de los formularios que tengan campos no obligatorios

2023-01-11 20:58 UTC, ldlsegovia approved these changes
👏🏻

2023-01-12 14:06 UTC, ttapia approved these changes
💎

2023-01-12 15:41 UTC, merged